### PR TITLE
Simplify codebase

### LINKED ISSUE #2: Simplify codebase
We should remove the flags that does not make sense in this context.

```
	flagset.BoolVar(&logging.toNatsServer, "logtonatsserver", true, "publish log to nats streaming server")
	flagset.StringVar(&logging.logDir, "log_dir", "", "If non-empty, write log files in this directory")
	flagset.StringVar(&logging.logFile, "log_file", "", "If non-empty, use this log file")
	flagset.BoolVar(&logging.toStderr, "logtostderr", false, "log to standard error instead of nats streaming server")
	flagset.BoolVar(&logging.alsoToStderr, "alsologtostderr", false, "log to standard error as well as nats streaming server")
	flagset.Var(&logging.verbosity, "v", "number for the log level verbosity")
	flagset.BoolVar(&logging.skipHeaders, "skip_headers", false, "If true, avoid header prefixes in the log messages")
	flagset.Var(&logging.stderrThreshold, "stderrthreshold", "logs at or above this threshold go to stderr")
	flagset.Var(&logging.vmodule, "vmodule", "comma-separated list of pattern=N settings for file-filtered logging")
	flagset.Var(&logging.traceLocation, "log_backtrace_at", "when logging hits line file:N, emit a stack trace")
```

### PR DESCRIPTION
**Pull request by masudur-rahman**
Fix #2

### CODE REVIEW

File: nats.go [hunk 1]
```diff
@@ -341,13 +294,8 @@ func InitFlags(flagset *flag.FlagSet) {
...
 	flagset.BoolVar(&logging.toNatsServer, "logtonatsserver", true, "publish log to nats streaming server")
-	flagset.StringVar(&logging.logDir, "log_dir", "", "If non-empty, write log files in this directory")
-	flagset.StringVar(&logging.logFile, "log_file", "", "If non-empty, use this log file")
-	flagset.BoolVar(&logging.toStderr, "logtostderr", false, "log to standard error instead of nats streaming server")
-	flagset.BoolVar(&logging.alsoToStderr, "alsologtostderr", false, "log to standard error as well as nats streaming server")
 	flagset.Var(&logging.verbosity, "v", "number for the log level verbosity")
 	flagset.BoolVar(&logging.skipHeaders, "skip_headers", false, "If true, avoid header prefixes in the log messages")
-	flagset.Var(&logging.stderrThreshold, "stderrthreshold", "logs at or above this threshold go to stderr")
 	flagset.Var(&logging.vmodule, "vmodule", "comma-separated list of pattern=N settings for file-filtered logging")
 	flagset.Var(&logging.traceLocation, "log_backtrace_at", "when logging hits line file:N, emit a stack trace")
```
Comment (tamalsaha) [inline nats.go]: Remove `traceLocation` flag and its logic.

File: nats.go [hunk 2]
```diff
@@ -421,26 +418,10 @@ where the fields are defined as follows:
...
-		slash := strings.LastIndex(file, "/")
-		if slash >= 0 {
-			file = file[slash+1:]
-		}
-	}
-	return l.formatHeader(s, file, line), file, line
-}
 
 // formatHeader formats a log header using the provided file name and line number.
-func (l *loggingT) formatHeader(s severity, file string, line int) *buffer {
```
Comment (tamalsaha) [inline nats.go]: We don't want to remove file and line number.

File: logger.go [hunk 3]
```diff
@@ -531,7 +463,7 @@ func (l *loggingT) formatHeader(s severity, file string, line int) *buffer {
 	buf.tmp[14] = '.'
 	buf.nDigits(6, 15, now.Nanosecond()/1000, '0')
 	buf.tmp[21] = ' '
-	buf.nDigits(7, 22, pid, ' ') // TODO: should be TID
+	buf.nDigits(7, 22, os.Getpid(), ' ') // TODO: should be TID
```
Comment (tamalsaha) [inline logger.go]: Globally
`var pid = os.Getpid()`
